// flow-typed signature: 966d558b3fa1bd3744db58dd76501d17
// flow-typed version: <<STUB>>/babel-plugin-regenerator_v^6.0.3/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-regenerator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-regenerator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-regenerator/lib/emit' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/lib/hoist' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/lib/leap' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/lib/meta' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/lib/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/lib/visit' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/main' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/runtime-module' {
  declare module.exports: any;
}

declare module 'babel-plugin-regenerator/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-regenerator/lib/emit.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/lib/emit'>;
}
declare module 'babel-plugin-regenerator/lib/hoist.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/lib/hoist'>;
}
declare module 'babel-plugin-regenerator/lib/leap.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/lib/leap'>;
}
declare module 'babel-plugin-regenerator/lib/meta.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/lib/meta'>;
}
declare module 'babel-plugin-regenerator/lib/util.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/lib/util'>;
}
declare module 'babel-plugin-regenerator/lib/visit.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/lib/visit'>;
}
declare module 'babel-plugin-regenerator/main.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/main'>;
}
declare module 'babel-plugin-regenerator/runtime-module.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/runtime-module'>;
}
declare module 'babel-plugin-regenerator/runtime.js' {
  declare module.exports: $Exports<'babel-plugin-regenerator/runtime'>;
}
