// flow-typed signature: 7da9891a5b2bd890155d8f9853a270bb
// flow-typed version: <<STUB>>/soundcloud_v^3.2.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'soundcloud'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'soundcloud' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'soundcloud/9f9aac32c9a7432b5555.worker' {
  declare module.exports: any;
}

declare module 'soundcloud/karma.conf' {
  declare module.exports: any;
}

declare module 'soundcloud/sdk' {
  declare module.exports: any;
}

declare module 'soundcloud/serve' {
  declare module.exports: any;
}

declare module 'soundcloud/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'soundcloud/9f9aac32c9a7432b5555.worker.js' {
  declare module.exports: $Exports<'soundcloud/9f9aac32c9a7432b5555.worker'>;
}
declare module 'soundcloud/index' {
  declare module.exports: $Exports<'soundcloud'>;
}
declare module 'soundcloud/index.js' {
  declare module.exports: $Exports<'soundcloud'>;
}
declare module 'soundcloud/karma.conf.js' {
  declare module.exports: $Exports<'soundcloud/karma.conf'>;
}
declare module 'soundcloud/sdk.js' {
  declare module.exports: $Exports<'soundcloud/sdk'>;
}
declare module 'soundcloud/serve.js' {
  declare module.exports: $Exports<'soundcloud/serve'>;
}
declare module 'soundcloud/webpack.config.js' {
  declare module.exports: $Exports<'soundcloud/webpack.config'>;
}
