import { NAME } from './constants';

export const SET_CURRENT_USER = `${NAME}/SET_CURRENT_USER`;

export const SET_USER = `${NAME}/SET_USER`;
export const SET_USERS = `${NAME}/SET_USERS`;

export const SET_USER_TRACKS = `${NAME}/SET_USER_TRACKS`;
export const SET_NEXT_USER_TRACKS = `${NAME}/SET_NEXT_USER_TRACKS`;

export const SET_FAVORITED_TRACKS = `${NAME}/SET_FAVORITED_TRACKS`;
export const SET_NEXT_FAVORITED_TRACKS = `${NAME}/SET_NEXT_FAVORITED_TRACKS`;

export const SET_USER_PLAYLISTS = `${NAME}/SET_USER_PLAYLISTS`;
export const SET_NEXT_USER_PLAYLISTS = `${NAME}/SET_NEXT_USER_PLAYLISTS`;
